name: grab_grip
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # auto_route is used for managing the routes between the about_us in the app.
  auto_route: ^2.3.2
  # cached_network_image is for showing images from the internet and caching them
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  # flash is for showing SnackBars easily
  flash: ^2.0.3
  flutter:
    sdk: flutter
  # flutter_html is used for rendering html coming from the server
  flutter_html: ^2.1.5
  flutter_localizations:
    sdk: flutter
  # flutter_riverpod is used for state management
  flutter_riverpod: ^0.14.0+3
  # google_geocoding is used to get the bounds of the location the user selects in browse screen
  google_geocoding: ^0.2.0
  google_maps_flutter: ^2.0.11
  # google_place is used to implement the autocomplete for the search box in browse screen
  google_place: ^0.4.3
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  json_annotation: ^4.1.0
  # material_floating_search_bar is used in browse screen for filtering gears by their locations
  material_floating_search_bar: ^0.3.5
  # multiple_result makes it easy to return two valued from a function
  multiple_result: ^1.0.4
  # retrofit is used for making http requests
  retrofit: ^2.0.1
  shared_preferences: ^2.0.8
  # skeleton_loader is for making loading skeleton
  skeleton_loader: ^2.0.0+4


dev_dependencies:
  # auto_route_generator is for generating code that is used for managing the routes between
  # the screens in the app.
  auto_route_generator: ^2.1.0
  build_runner: ^2.1.2
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  # freezed is used for code generation for unions and more
  freezed: ^0.14.5
  json_serializable: ^5.0.2
  lint: ^1.7.2
  retrofit_generator: ^2.0.1+1

# override the analyzer dependency to solve an issue related to the usage of the auto_route package.
#dependency_overrides:
#  analyzer: ^1.7.0

# the following is for customizing the app icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: NeoTech
      fonts:
        - asset: assets/fonts/NeoTech.otf
  #          style: italic
  #          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
